services:
  - type: web
    name: waterborne-risk-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MODEL_PATH
        value: water_quality/models/model.pkl
